### ISSUE TITLE
What license is this project released under?

### ISSUE THREAD

**Issue by allejo** [TomWright/mermaid-server#138]
I can't find anything specifying what license this project is released under.

**Comment by TomWright** [comment]
Sorry completely forgot to add a license. Consider it MIT, free to do with what you want but provided as-is.

**Comment by moryak2020** [comment]
What is it ?

пт, 20 дек. 2024 г., 01:15 Tom Wright ***@***.***>:

**Comment by TomWright** [comment]
I've now added a [LICENSE](https://github.com/TomWright/mermaid-server/blob/master/LICENSE) file.
